from __future__ import annotations

from uuid import uuid4

from backend.core.media_asset import MediaAsset
from backend.services.vision_provider import VisionProvider


class DefaultVisionProvider(VisionProvider):
    """Default placeholder vision provider for architecture validation."""

    async def analyze_image(self, *, source: str, prompt: str | None = None) -> tuple[MediaAsset, list[dict[str, str]]]:
        asset = MediaAsset(
            id=str(uuid4()),
            type="image",
            source=source,
            provider="default-vision",
            mime_type="image/unknown",
            prompt=prompt,
            metadata={"placeholder": True},
        )
        observations = [
            {
                "label": "summary",
                "value": "Placeholder analysis generated by default vision provider.",
            },
            {
                "label": "safety",
                "value": "No provider-specific policy result available in placeholder mode.",
            },
        ]
        return asset, observations
